config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

#book関連ルート
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

#users関連ルート
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create,:destroy]
    get 'relationships/followers'=>'relationships#followers',as: 'follower'
    get 'relationships/followings'=>'relationships#followings',as: 'following'
  end

#検索関連ルート
  get 'searches/search'=>'searches#search',as: 'search'

#グループ機能用ルート
  resources :groups do
    post 'groups/join'=>'groups#join',as: 'join'
    delete 'groups/withdrawal'=>'groups#withdrawal',as: 'withdrawal'
    get 'new/mail'=>'groups#new_mail'
    get 'send/mail'=>'groups#send_mail'
  end

#チャット関連ルート
  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy

#いいね機能のアソシエーション
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

#閲覧数表示のアソシエーション
  has_many :view_counts, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

#いいねが存在しているか
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

#検索機能
  def self.search_for(word,method)
    if method == 'perfect'
      Book.where(title: word)
    elsif method == 'forward'
      Book.where('title LIKE ?',"#{word}%")
    elsif method == 'backward'
      Book.where('title LIKE ?',"%#{word}")
    elsif method == 'partial'
      Book.where('title LIKE ?',"%#{word}%")
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user

  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end

  def user_join?(user)
    group_users.where(user_id: user).exists?
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/room.rb
class Room < ApplicationRecord

  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

# フォロー機能のアソシエーション
  has_many :relationships, class_name: 'Relationship', foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :relationships, source: :follower
  has_many :reverce_of_relationships, class_name: 'Relationship', foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :reverce_of_relationships, source: :followed

# DM機能のアソシエーション
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

#閲覧数表示のアソシエーション
  has_many :view_counts, dependent: :destroy

#グループ機能のアソシエーション
  has_many :group_users, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

# ユーザープロフィール画像
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

# フォロー機能
  def follow(user)
    reverce_of_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    reverce_of_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

# 検索機能
  def self.search_for(word,method)
    if method == 'perfect'
      User.where(name: word)
    elsif method == 'forward'
      User.where('name LIKE ?', "#{word}%")
    elsif method == 'backward'
      User.where('name LIKE ?', "%#{word}")
    elsif method == 'partial'
      User.where('name LIKE ?', "%#{word}%")
    end
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    unless ViewCount.find_by(user_id: current_user.id,book_id: @book.id)
      ViewCount.create(user_id: current_user.id,book_id: @book.id)
    end
    @book_comment = BookComment.new
  end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    #Bookに関連するfavorited_usersの内容をまとめて取得
    #favorited_users=その本に対していいねしたユーザー
    #(Book.favoritesだと対象になる本のidまで持ってきてしまうため比較できない)
    @books = Book.includes(:favorited_users).
      sort {|a,b|
        b.favorited_users.where(created_at: from...to).size <=>
        a.favorited_users.where(created_at: from...to).size
      }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/relationships/_btn.html.erb
<% if user != current_user %>
  <% if current_user.following?(user) %>
    <%= link_to 'un follow', user_relationships_path(user), method: :delete, remote: true, class: 'btn-flat-border-after' %>
  <% else %>
    <%= link_to 'follow', user_relationships_path(user), method: :post, remote: true, class: 'btn-flat-border-before' %>
  <% end %>
<% end %>

app/views/relationships/_count.html.erb
<tr>
  <th>followed</th>
  <th><%= link_to user.followings.count, user_following_path(user) %></th>
</tr>
<tr>
  <th>follower</th>
  <th><%= link_to user.followers.count, user_follower_path(user) %></th>
</tr>

app/views/relationships/_index.html.erb
<table class="table">
        <thead>
          <tr>
            <th></th>
            <th>ユーザー名</th>
            <th>紹介文</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image, size:"50x50" %></td>
            <td><%= user.name %></td>
            <td><%= user.introduction %></td>
            <td>フォロー数:<%= user.followings.count %></td>
            <td>フォロワー数:<%= user.followers.count %></td>
            <td><%= render 'btn', user: user %></td>
            <td><%= link_to "Show", user_path(user) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/relationships/create.js.erb
$(".follow_<%= @user.id %>").html("<%= j(render 'relationships/btn', user: @user) %>");
$(".follow_count").html("<%= j(render 'relationships/count', user: @user) %>");
$(".current_users_follow_count").html("<%= j(render 'relationships/count', user: current_user) %>");

app/views/relationships/destroy.js.erb
$(".follow_<%= @user.id %>").html("<%= j(render 'relationships/btn', user: @user) %>");
$(".follow_count").html("<%= j(render 'relationships/count', user: @user) %>");
$(".current_users_follow_count").html("<%= j(render 'relationships/count', user: current_user) %>");

app/views/relationships/followers.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <h2>フォロワー</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <h2>フォロワー</h2>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>