config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

#book関連ルート
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

#users関連ルート
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create,:destroy]
    get 'relationships/followers'=>'relationships#followers',as: 'follower'
    get 'relationships/followings'=>'relationships#followings',as: 'following'
  end

#検索関連ルート
  get 'searches/search'=>'searches#search',as: 'search'

#グループ機能用ルート
  resources :groups do
    post 'groups/join'=>'groups#join',as: 'join'
    delete 'groups/withdrawal'=>'groups#withdrawal',as: 'withdrawal'
    get 'new/mail'=>'groups#new_mail'
    get 'send/mail'=>'groups#send_mail'
  end

#チャット関連ルート
  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user

  has_one_attached :group_image

  def get_group_image
    (group_image.attached?) ? group_image : 'no_image.jpg'
  end

  def user_join?(user)
    group_users.where(user_id: user).exists?
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
    @book = Book.new
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    @group.save
    redirect_to groups_path
  end

  def show
    @group = Group.find(params[:id])
    @book = Book.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.update(group_params)
    redirect_to groups_path
  end

  def join
    @group = Group.find(params[:group_id])
    current_user.group_users.create(group_id: @group.id)
    redirect_to groups_path
  end

  def withdrawal
    @group = Group.find(params[:group_id])
    current_user.group_users.find_by(group_id: @group.id).destroy
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:group_image)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group do |f| %>
  <div class="form-group">
    <%= f.label :name, "グループ名" %>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :group_image, "グループ画像" %>
    <%= f.file_field :group_image, class:"form-control-file" %>
  </div>
  <div class="form-group">
    <%= f.label :introduction, "紹介文" %>
    <%= f.text_area :introduction, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn-flat-success" %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td><%= image_tag group.get_group_image, size: "50x50" %></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= group.introduction %></td>
      <td><%= group.users.count %></td>
      <td>
        <% if group.owner_id == current_user.id %>
          <%= link_to "Edit", edit_group_path(group), class:"btn btn-success" %>
        <% else %>
          <% if group.user_join?(current_user) %>
            <%= link_to "Withdrawal", group_withdrawal_path(group), class:"btn_20", method: :delete %>
          <% else %>
            <%= link_to "Join", group_join_path(group), class:"btn_19", method: :post %>
          <% end %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>グループ編集</h2>
      <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-lg-8 offset-md-1">
      <h2>Groups</h2>
      <%= link_to "グループ一覧", groups_path %> | <%= link_to "グループ作成", new_group_path %>
      <%= render "index", groups: @groups %>
    </div>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>グループ作成</h2>
      <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2 class="under_line2">メンバーへのメール</h2>
      <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.label :mail_title %>
          <%= f.text_field :mail_title, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :mail_content %>
          <%= f.text_area :mail_content, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit "送信" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <div class="margin_top">内容は以下の通りです。</div>
      <p>タイトル</p><br>
      <p><strong><%= @mail_title %></strong></p>
      <p>本文</p>
      <p><strong><%= safe_join(@mail_content.split("\n"),tag(:br)) %></strong></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <h2 class="under_line2">User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3 under_line2">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-lg-8 offset-md-1">
      <h2 class="under_line2">Group detail</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image, size: '50x50' %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |user| %>
              <li class="list-unstyled">
                <%= user.name %>
              </li>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class:"btn btn-success" %>
              <% else %>
                <% if @group.user_join?(current_user) %>
                  <%= link_to "Withdrawal", group_withdrawal_path(@group), class:"btn_20", method: :delete %>
                <% else %>
                  <%= link_to "Join", group_join_path(@group), class:"btn_19", method: :post %>
                <% end %>
              <% end %>
            </td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Mail", group_new_mail_path(@group), class:"btn btn-primary" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>