config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

#book関連ルート
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

#users関連ルート
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only:[:create,:destroy]
    get 'relationships/followers'=>'relationships#followers',as: 'follower'
    get 'relationships/followings'=>'relationships#followings',as: 'following'
  end

#検索関連ルート
  get 'searches/search'=>'searches#search',as: 'search'

#グループ機能用ルート
  resources :groups do
    post 'groups/join'=>'groups#join',as: 'join'
    delete 'groups/withdrawal'=>'groups#withdrawal',as: 'withdrawal'
    get 'new/mail'=>'groups#new_mail'
    get 'send/mail'=>'groups#send_mail'
  end

#チャット関連ルート
  resources :chats, only: [:show, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_one_attached :profile_image

# フォロー機能のアソシエーション
  has_many :relationships, class_name: 'Relationship', foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :relationships, source: :follower
  has_many :reverce_of_relationships, class_name: 'Relationship', foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :reverce_of_relationships, source: :followed

# DM機能のアソシエーション
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
  has_many :rooms, through: :user_rooms

#閲覧数表示のアソシエーション
  has_many :view_counts, dependent: :destroy

#グループ機能のアソシエーション
  has_many :group_users, dependent: :destroy

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

# ユーザープロフィール画像
  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

# フォロー機能
  def follow(user)
    reverce_of_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    reverce_of_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

# 検索機能
  def self.search_for(word,method)
    if method == 'perfect'
      User.where(name: word)
    elsif method == 'forward'
      User.where('name LIKE ?', "#{word}%")
    elsif method == 'backward'
      User.where('name LIKE ?', "%#{word}")
    elsif method == 'partial'
      User.where('name LIKE ?', "%#{word}%")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td class="follow_<%= user.id %>"><%= render 'relationships/btn',user: user %></td>
        <td><%= link_to 'Show', user, class: "btn-border-bottom" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <% if current_page?(users_path) %>
    <table class="table current_users_follow_count">
      <%= render 'relationships/count', user: user %>
    </table>
  <% else %>
    <table class="table follow_count">
      <%= render 'relationships/count', user: user %>
    </table>
  <% end %>
</table>

<div class='row'>
  <% if current_user == user %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% else %>
    <div class="follow_<%= user.id %>">
      <%= render 'relationships/btn', user: user %>
    </div>
  <% end %>

  <% if current_user != user && (current_user.following?(user) && user.following?(current_user)) %>
    <%= link_to 'chatを始める', chat_path(user.id), class:"btn btn-primary ml-3" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-3">
      <h2 class="under_line2">User infi</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3 under_line2">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-lg-8 offset-md-1">
      <h2 class="under_line2">Users</h2>
      <%= link_to "グループ一覧", groups_path %> | <%= link_to "グループ作成", new_group_path %>
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>